url: "rosewills.github.io/infinite-loops"			# Hostname & protocol of site (e.g. http://example.com)
baseurl: ""							# Subpath of site (e.g. /blog)
title: "Infinite Loops"				# Name of site (e.g. ACME Corp.)
description: "Science with yarn, and yarns about science."


exclude:							# Ignore these directories when generating the site
  - "/vendor/"
  - "/template/"
  - ".obsidian/"
  - "ofiles/"
